# Generated by Django 5.0.1 on 2024-04-22 17:30

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorInicial', models.FloatField()),
                ('valorAtual', models.FloatField()),
                ('dataHoraAberturaAtual', models.CharField(max_length=55)),
                ('isOpen', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=105)),
                ('cep', models.CharField(max_length=105)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('numTelefone', models.CharField(max_length=11, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('dataNascimento', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='DiaCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataHoraAbertura', models.CharField(max_length=55)),
                ('dataHoraEncerramento', models.CharField(max_length=55)),
                ('valorInicial', models.FloatField()),
                ('valorFinal', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='EntradaMercadoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('data', models.CharField(max_length=55)),
                ('valor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MetodoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(max_length=55)),
                ('valor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoBarras', models.CharField(max_length=155)),
                ('nome', models.CharField(max_length=155)),
                ('tipo', models.CharField(max_length=55)),
                ('dataValidade', models.CharField(max_length=55)),
                ('qtdMinima', models.IntegerField()),
                ('quantidade', models.IntegerField()),
                ('valor', models.FloatField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=55)),
                ('total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=128)),
                ('password2', models.CharField(max_length=128)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=105)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.pessoa')),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('rg', models.CharField(max_length=9, unique=True)),
            ],
            bases=('core.pessoa',),
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.pessoa')),
                ('cnpj', models.CharField(max_length=14, unique=True)),
            ],
            bases=('core.pessoa',),
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.pessoa')),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('cargo', models.CharField(max_length=55)),
                ('salario', models.FloatField()),
                ('cargaHoraria', models.FloatField()),
            ],
            bases=('core.pessoa',),
        ),
        migrations.CreateModel(
            name='Caixa_DiaCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownerCaixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.caixa')),
                ('ownerDiaCaixa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.diacaixa')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=55)),
                ('numCasa', models.CharField(max_length=10)),
                ('complemento', models.CharField(max_length=55)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.bairro')),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('dataVencimento', models.CharField(max_length=55)),
                ('tipoReceber', models.BooleanField()),
                ('ownerEntradaMercadoria', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.entradamercadoria')),
                ('ownerVenda', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.venda')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=105)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.pessoa')),
            ],
        ),
        migrations.AddField(
            model_name='cidade',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.estado'),
        ),
        migrations.CreateModel(
            name='EntradaMercadoria_MetodoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownerEntradaMercadoria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.entradamercadoria')),
                ('ownerMetodoPagamento', models.ManyToManyField(to='core.metodopagamento')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=55)),
                ('valor', models.FloatField()),
                ('ownerCaixa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.caixa')),
                ('ownerConta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.conta')),
            ],
        ),
        migrations.CreateModel(
            name='EntradaMercadoria_Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownerEntradaMercadoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.entradamercadoria')),
                ('ownerProduto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Venda_MetodoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownerMetodoPagamento', models.ManyToManyField(to='core.metodopagamento')),
                ('ownerVenda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.venda')),
            ],
        ),
        migrations.CreateModel(
            name='VendaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('valor', models.FloatField()),
                ('ownerProduto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.produto')),
                ('ownerVenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.venda')),
            ],
        ),
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=55)),
                ('ownerVenda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.venda')),
                ('listVendaProduto', models.ManyToManyField(to='core.vendaproduto')),
            ],
        ),
        migrations.AddField(
            model_name='venda',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente'),
        ),
        migrations.AddField(
            model_name='entradamercadoria',
            name='ownerFornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fornecedor'),
        ),
    ]
