# Generated by Django 5.0.1 on 2024-05-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_password_alter_customuser_password2'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='dataDoDesativ0',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
