# Generated by Django 5.0.1 on 2024-05-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_pessoa_datadodesativ0_pessoa_datadodesativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendaproduto',
            name='dataDoDesativo',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='vendaproduto',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
