# Generated by Django 5.0.1 on 2024-06-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_vendaproduto_datadodesativo_vendaproduto_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='typeOwner',
            field=models.CharField(default=1, max_length=55),
            preserve_default=False,
        ),
    ]
