# Generated by Django 5.0.1 on 2024-08-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_estado_typeowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='resolvida',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
