# Generated by Django 5.0.4 on 2024-08-15 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_conta_resolvida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradamercadoria_metodopagamento',
            name='ownerEntradaMercadoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.entradamercadoria'),
        ),
        migrations.RemoveField(
            model_name='entradamercadoria_metodopagamento',
            name='ownerMetodoPagamento',
        ),
        migrations.AddField(
            model_name='entradamercadoria_metodopagamento',
            name='ownerMetodoPagamento',
            field=models.CharField(default='pix', max_length=55),
            preserve_default=False,
        ),
    ]
