import Head from 'next/head'
import React from "react";
import '../styles/globals.css'

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
  }

export default function MyApp({ Component, pageProps }) {

  return(
    <div>
        <Head>
          <meta http-equiv="X-UA-Compatible" content="IE=edge"></meta>
          <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
        </Head>
        <Component {...pageProps} />
    </div>
  )

}